/**
 * GlobeTrotter Curated Destinations Data Model
 * All homepage datasets stored cleanly inside the tirth folder.
 */

export const HERO_DESTINATIONS = [
  {
    id: "lago-di-braies",
    slideNumber: "01",
    country: "Italy",
    region: "The Dolomites",
    title: "Lago di Braies",
    description: "A crystal-clear alpine lake surrounded by dramatic Dolomite peaks, emerald forests, and iconic wooden rowboats.",
    image: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1920&q=85",
    imageAlt: "Wooden boats floating on the turquoise water of Lago di Braies beneath the Dolomite mountains",
    duration: "4–6 Days",
    bestSeason: "May–September",
    travelStyle: "Nature & Photography",
  },
  {
    id: "reykjavik",
    slideNumber: "02",
    country: "Iceland",
    region: "Golden Circle & South Coast",
    title: "Reykjavik & Wild Coast",
    description: "Chasing northern lights, geothermal springs, volcanic crater lakes, and black sand shores at the edge of the Arctic.",
    image: "https://images.unsplash.com/photo-1504893524553-b855bce32c67?auto=format&fit=crop&w=1920&q=85",
    imageAlt: "Vibrant aurora borealis dancing over Icelandic snow capped mountains",
    duration: "7–10 Days",
    bestSeason: "September–March",
    travelStyle: "Adventure & Aurora",
  },
  {
    id: "santorini",
    slideNumber: "03",
    country: "Greece",
    region: "Cyclades, Aegean Sea",
    title: "Santorini Caldera",
    description: "Whitewashed Cycladic cliffs, azure domes, world-famous golden sunsets, and volcanic vineyard retreats.",
    image: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=1920&q=85",
    imageAlt: "Famous white buildings with blue domes in Santorini",
    duration: "5–7 Days",
    bestSeason: "May–October",
    travelStyle: "Relaxation & Culture",
  },
  {
    id: "amalfi-coast",
    slideNumber: "04",
    country: "Italy",
    region: "Campania Coastline",
    title: "Amalfi Coastline",
    description: "Pastel cliffside villages, limoncello orchards, dramatic coastal roads, and private Mediterranean catamaran cruises.",
    image: "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1920&q=85",
    imageAlt: "Colorful houses on Positano cliffside tumbling to the Mediterranean",
    duration: "6–8 Days",
    bestSeason: "April–October",
    travelStyle: "Coastal & Food",
  },
  {
    id: "kyoto",
    slideNumber: "05",
    country: "Japan",
    region: "Kansai Region",
    title: "Kyoto Teahouses",
    description: "Serene bamboo groves, traditional Machiya teahouses, moss gardens, and historic wooden Zen temples.",
    image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1920&q=85",
    imageAlt: "Wooden pagoda surrounded by cherry blossoms in Kyoto",
    duration: "6–10 Days",
    bestSeason: "March–May",
    travelStyle: "Culture & History",
  },
  {
    id: "machu-picchu",
    slideNumber: "06",
    country: "Peru",
    region: "Andes Mountains",
    title: "Machu Picchu Citadel",
    description: "Trek high-altitude Inca trails through cloud forests, exploring ancient stone sanctuaries above the Urubamba valley.",
    image: "https://images.unsplash.com/photo-1587595431973-160d0d94add1?auto=format&fit=crop&w=1920&q=85",
    imageAlt: "Mist floating over stone ruins of Machu Picchu",
    duration: "8–12 Days",
    bestSeason: "April–October",
    travelStyle: "Trekking & History",
  },
];

export const FEATURED_CARDS = [
  {
    id: "reykjavik",
    country: "ICELAND",
    title: "Volcanic Aurora Quest",
    location: "Reykjavik & Ring Road",
    duration: "8 Days",
    bestSeason: "Oct – Mar",
    travelStyle: "Highland Expedition",
    image: "https://images.unsplash.com/photo-1504893524553-b855bce32c67?auto=format&fit=crop&w=1000&q=85",
    imageAlt: "Northern lights in Iceland",
    featured: true,
  },
  {
    id: "amalfi-coast",
    country: "ITALY",
    title: "Coastal Cliff Escape",
    location: "Positano & Capri",
    duration: "7 Days",
    bestSeason: "May – Sep",
    travelStyle: "Mediterranean",
    image: "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1000&q=85",
    imageAlt: "Amalfi Coast Positano cliffs",
  },
  {
    id: "santorini",
    country: "GREECE",
    title: "Aegean Sunset Retreat",
    location: "Oia & Fira",
    duration: "5 Days",
    bestSeason: "Jun – Sep",
    travelStyle: "Island Sanctuary",
    image: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=1000&q=85",
    imageAlt: "Santorini caldera view",
  },
  {
    id: "lisbon",
    country: "PORTUGAL",
    title: "Sunlit Cobblestones",
    location: "Alfama & Sintra",
    duration: "6 Days",
    bestSeason: "Apr – Oct",
    travelStyle: "Heritage Walk",
    image: "https://images.unsplash.com/photo-1509803874385-db7c23652552?auto=format&fit=crop&w=1000&q=85",
    imageAlt: "Lisbon yellow tram and historic streets",
  },
  {
    id: "swiss-alps",
    country: "SWITZERLAND",
    title: "Glacier Rail Odyssey",
    location: "Zermatt & Grindelwald",
    duration: "9 Days",
    bestSeason: "Dec – Mar",
    travelStyle: "Alpine Rail",
    image: "https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=1000&q=85",
    imageAlt: "Swiss Alps snowy mountains and train",
  },
  {
    id: "paris",
    country: "FRANCE",
    title: "Bohemian Seine Promenade",
    location: "Montmartre & Le Marais",
    duration: "5 Days",
    bestSeason: "Year Round",
    travelStyle: "Cultural Arts",
    image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1000&q=85",
    imageAlt: "Eiffel Tower and Paris streets",
  },
];
