/**
 * GlobeTrotter Community Dataset ("The Travel Atlas")
 * 10 Public Journeys, 7 Travel Moods, and 6 Traveler Profiles.
 */

export const TRAVEL_MOODS = [
  {
    id: "mood-slow",
    title: "SLOW ESCAPES",
    subtitle: "Quiet cafés · villages · nature",
    image: "/assets/cities/kyoto.png",
    category: "slow",
    color: "from-emerald-900/80 to-teal-950/90",
    border: "border-emerald-500/30",
    accent: "#7FB3A3",
  },
  {
    id: "mood-solo",
    title: "FIRST SOLO TRIP",
    subtitle: "Independent · exciting · flexible",
    image: "/assets/cities/paris.png",
    category: "solo",
    color: "from-amber-900/80 to-orange-950/90",
    border: "border-amber-500/30",
    accent: "#E9C98A",
  },
  {
    id: "mood-food",
    title: "FOODIE TRAILS",
    subtitle: "Markets · street food · local flavors",
    image: "/assets/activities/foodtour.png",
    category: "food",
    color: "from-rose-900/80 to-pink-950/90",
    border: "border-rose-500/30",
    accent: "#FDA4AF",
  },
  {
    id: "mood-weekend",
    title: "WEEKEND RESET",
    subtitle: "2–3 days · easy escapes",
    image: "/assets/cities/rome.png",
    category: "weekend",
    color: "from-sky-900/80 to-indigo-950/90",
    border: "border-sky-500/30",
    accent: "#7DD3FC",
  },
  {
    id: "mood-adventure",
    title: "ADVENTURE MODE",
    subtitle: "Treks · diving · road trips",
    image: "/assets/activities/paragliding.png",
    category: "adventure",
    color: "from-blue-900/80 to-cyan-950/90",
    border: "border-cyan-500/30",
    accent: "#67E8F9",
  },
  {
    id: "mood-romantic",
    title: "ROMANTIC GETAWAYS",
    subtitle: "Sunsets · cities · hidden stays",
    image: "/assets/cities/santorini.png",
    category: "romantic",
    color: "from-purple-900/80 to-fuchsia-950/90",
    border: "border-purple-500/30",
    accent: "#C084FC",
  },
  {
    id: "mood-budget",
    title: "BUDGET EXPLORERS",
    subtitle: "Smart · affordable · memorable",
    image: "/assets/cities/istanbul.png",
    category: "budget",
    color: "from-amber-950/80 to-yellow-950/90",
    border: "border-yellow-500/30",
    accent: "#FCD34D",
  },
];

export const TRAVELERS = [
  {
    id: "user-maya",
    username: "@maya",
    name: "Maya Lin",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80",
    style: "FOOD · CULTURE · SLOW TRAVEL",
    journeysCount: 12,
    countriesCount: 8,
    homeCity: "Singapore",
    bio: "Obsessed with sunrise tea ceremonies, finding hidden ramen alleys, and slow train routes across Asia and Europe.",
    stamps: ["🇯🇵 Japan", "🇮🇹 Italy", "🇫🇷 France", "🇹🇭 Thailand", "🇻🇳 Vietnam"],
    isVerified: true,
  },
  {
    id: "user-aarav",
    username: "@aarav",
    name: "Aarav Sharma",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80",
    style: "ADVENTURE · PHOTOGRAPHY",
    journeysCount: 9,
    countriesCount: 6,
    homeCity: "Bengaluru, India",
    bio: "Chasing golden hour shadows over mountain peaks and capturing underwater wildlife stories.",
    stamps: ["🇮🇩 Indonesia", "🇰🇪 Kenya", "🇳🇵 Nepal", "🇲🇻 Maldives"],
    isVerified: true,
  },
  {
    id: "user-elena",
    username: "@elena_v",
    name: "Elena Vasquez",
    avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80",
    style: "COASTAL · ROMANTIC · LUXURY",
    journeysCount: 15,
    countriesCount: 11,
    homeCity: "Barcelona, Spain",
    bio: "Seeking pastel cliffside villages, vintage convertible drives, and quiet Aegean sea breezes.",
    stamps: ["🇬🇷 Greece", "🇮🇹 Italy", "🇪🇸 Spain", "🇵🇹 Portugal", "🇲🇦 Morocco"],
    isVerified: true,
  },
  {
    id: "user-kenji",
    username: "@kenji_t",
    name: "Kenji Takahashi",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80",
    style: "ALPINE · RAIL TRAVEL · MINIMALIST",
    journeysCount: 8,
    countriesCount: 5,
    homeCity: "Tokyo, Japan",
    bio: "Minimalist backpacker exploring scenic mountain railways, blue glaciers, and wooden architecture.",
    stamps: ["🇨🇭 Switzerland", "🇮🇸 Iceland", "🇳🇴 Norway", "🇯🇵 Japan"],
    isVerified: false,
  },
  {
    id: "user-liam",
    username: "@liam_wander",
    name: "Liam O'Connor",
    avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=400&q=80",
    style: "SOLO TRAVEL · BUDGET · BACKPACKING",
    journeysCount: 14,
    countriesCount: 12,
    homeCity: "Dublin, Ireland",
    bio: "Traveling light across cobblestone cities, staying in historic quarters, and collecting local stories.",
    stamps: ["🇹🇷 Turkey", "🇨🇿 Czechia", "🇲🇦 Morocco", "🇻🇳 Vietnam", "🇵🇹 Portugal"],
    isVerified: true,
  },
  {
    id: "user-priya",
    username: "@priya_travels",
    name: "Priya Mehta",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80",
    style: "ROAD TRIPS · HERITAGE · CULINARY",
    journeysCount: 10,
    countriesCount: 4,
    homeCity: "Mumbai, India",
    bio: "Road trip fanatic discovering royal palaces, desert fortresses, and regional street food culture.",
    stamps: ["🇮🇳 India", "🇴🇲 Oman", "🇱🇰 Sri Lanka", "🇦🇪 UAE"],
    isVerified: true,
  },
];

export const COMMUNITY_JOURNEYS = [
  {
    id: "comm-japan-1",
    isFeatured: true,
    title: "JAPAN, UNFILTERED",
    subtitle: "7 DAYS IN JAPAN",
    route: "Tokyo → Kyoto → Osaka",
    quote: "A first-time journey through neon nights, quiet temples and too much ramen.",
    destination: "Japan",
    citiesCount: 3,
    duration: "7 Days",
    budget: "₹82,000",
    budgetCategory: "mid",
    season: "Spring",
    groupType: "Solo",
    moodCategory: "food",
    styles: ["FOOD", "CULTURE", "SLOW TRAVEL"],
    creator: TRAVELERS[0], // @maya
    savesCount: 348,
    image: "/assets/cities/tokyo.png",
    heroImage: "/assets/cities/kyoto.png",
    description: "An authentic 7-day loop connecting Tokyo's futuristic neon districts, Kyoto's ancient bamboo groves and serene zen teahouses, ending with Osaka's sizzling street food culture.",
    timeline: [
      {
        day: 1,
        title: "Neon Arrivals & Shibuya Sky",
        location: "Tokyo",
        activities: ["Shibuya Crossing at twilight", "Observation deck view from Shibuya Sky", "Late-night Tonkotsu Ramen in Shinjuku"],
        image: "/assets/cities/tokyo.png",
        timing: "Morning to Late Night",
        cost: "₹11,500",
        notes: "Pick up Suica transport card at Haneda Airport. Best sunset photos from Shibuya Sky south edge."
      },
      {
        day: 2,
        title: "Senso-ji & Digital Art Realm",
        location: "Tokyo",
        activities: ["Dawn walk at Senso-ji Temple in Asakusa", "Matcha tea ceremony at Traditional Garden", "teamLab Planets immersive light exhibit"],
        image: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=800&q=80",
        timing: "08:00 AM – 09:00 PM",
        cost: "₹9,800",
        notes: "Book teamLab tickets at least 2 weeks in advance."
      },
      {
        day: 3,
        title: "Shinkansen Bullet Train to Kyoto",
        location: "Tokyo → Kyoto",
        activities: ["Hop on Hikari Shinkansen past Mt. Fuji", "Check into traditional Machiya Guesthouse", "Evening stroll in Gion lantern district"],
        image: "/assets/cities/kyoto.png",
        timing: "10:00 AM – 08:00 PM",
        cost: "₹14,200",
        notes: "Sit on right side (Seat E) for clear view of Mount Fuji during bullet train ride."
      },
      {
        day: 4,
        title: "Bamboo Grove & Torii Gates",
        location: "Kyoto",
        activities: ["06:30 AM Arashiyama Bamboo Grove walk", "Togetsukyo Bridge views", "Fushimi Inari Shrine dawn summit hike"],
        image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=800&q=80",
        timing: "06:00 AM – 04:00 PM",
        cost: "₹6,500",
        notes: "Arrive at bamboo grove before 7 AM to experience silence without crowd."
      },
      {
        day: 5,
        title: "Golden Pavilion & Nishiki Market",
        location: "Kyoto",
        activities: ["Kinkaku-ji Golden Pavilion", "Ryoan-ji Zen rock garden", "Food tasting at Nishiki Market (Dango & Wagyu skewers)"],
        image: "https://images.unsplash.com/photo-1492571350019-22de08371fd3?auto=format&fit=crop&w=800&q=80",
        timing: "09:00 AM – 06:00 PM",
        cost: "₹8,400",
        notes: "Nishiki market vendors prefer cash payments."
      },
      {
        day: 6,
        title: "Osaka Street Food Capital",
        location: "Osaka",
        activities: ["Local train to Osaka", "Osaka Castle Park walk", "Dotonbori neon alleyways, Takoyaki & Okonomiyaki feast"],
        image: "https://images.unsplash.com/photo-1590559899731-a382839e5549?auto=format&fit=crop&w=800&q=80",
        timing: "11:00 AM – Midnight",
        cost: "₹12,600",
        notes: "Try famous Glico Running Man photo spot along canal bridge."
      },
      {
        day: 7,
        title: "Kuromon Market & Farewell",
        location: "Osaka",
        activities: ["Kuromon Ichiba morning seafood market", "Souvenir shopping in Shinsaibashi", "Kansai Airport departure"],
        image: "/assets/activities/foodtour.png",
        timing: "09:00 AM – 04:00 PM",
        cost: "₹19,000",
        notes: "Buy Tokyo Banana and KitKat matcha regional gifts before flight."
      }
    ]
  },
  {
    id: "comm-bali-2",
    isFeatured: false,
    title: "BALI SANCTUARY & WAVES",
    subtitle: "5 DAYS IN BALI",
    route: "Ubud → Canggu",
    quote: "Emerald rice terraces, sunrise volcano hikes, and quiet surf breaks.",
    destination: "Indonesia",
    citiesCount: 2,
    duration: "5 Days",
    budget: "₹45,000",
    budgetCategory: "budget",
    season: "Summer",
    groupType: "Solo",
    moodCategory: "slow",
    styles: ["BEACH", "WELLNESS", "ADVENTURE"],
    creator: TRAVELERS[1], // @aarav
    savesCount: 284,
    image: "/assets/cities/bali.png",
    heroImage: "/assets/cities/bali.png",
    description: "A refreshing 5-day escape immersing in Ubud's lush jungle retreats, Tegallalang rice paddies, and Canggu's vibrant beach club sunsets.",
    timeline: [
      {
        day: 1,
        title: "Ubud Jungle Check-in",
        location: "Ubud",
        activities: ["Private villa pool relaxation", "Sacred Monkey Forest Sanctuary", "Traditional Balinese organic dinner"],
        image: "/assets/cities/bali.png",
        timing: "12:00 PM – 09:00 PM",
        cost: "₹8,500",
        notes: "Keep sunglasses secure around monkeys in forest sanctuary."
      },
      {
        day: 2,
        title: "Rice Terraces & Temple Water Ritual",
        location: "Ubud",
        activities: ["Tegallalang Rice Terrace morning walk", "Tirta Empul Holy Water Temple purification ritual", "Tegenungan Waterfall swim"],
        image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=800&q=80",
        timing: "07:00 AM – 05:00 PM",
        cost: "₹7,200",
        notes: "Sarong required for temple entrance (included with ticket)."
      },
      {
        day: 3,
        title: "Mount Batur Sunrise Trek",
        location: "Kintamani → Canggu",
        activities: ["03:00 AM Mount Batur active volcano sunrise hike", "Geothermal hot springs swim", "Transfer to Canggu coastal town"],
        image: "https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?auto=format&fit=crop&w=800&q=80",
        timing: "02:30 AM – 04:00 PM",
        cost: "₹10,500",
        notes: "Headlamps and breakfast at summit provided by trek guide."
      },
      {
        day: 4,
        title: "Canggu Surf & Beach Sunsets",
        location: "Canggu",
        activities: ["Morning beginner surf lesson at Batu Bolong Beach", "Açai smoothie bowl brunch", "Sunset drinks at Echo Beach"],
        image: "/assets/activities/kayaking.png",
        timing: "08:00 AM – 08:00 PM",
        cost: "₹9,800",
        notes: "Rent scooter for easy navigation around Canggu shortcut."
      },
      {
        day: 5,
        title: "Uluwatu Cliff & Departure",
        location: "Uluwatu",
        activities: ["Uluwatu Sea Temple clifftop viewpoint", "Kecak Fire Dance performance", "Airport transfer"],
        image: "https://images.unsplash.com/photo-1555400038-63f5ba517a47?auto=format&fit=crop&w=800&q=80",
        timing: "10:00 AM – 08:00 PM",
        cost: "₹9,000",
        notes: "Book Kecak dance tickets online early to avoid sold-out sunset show."
      }
    ]
  },
  {
    id: "comm-rajasthan-3",
    isFeatured: false,
    title: "RAJASTHAN ROYAL ROAD TRIP",
    subtitle: "6 DAYS IN INDIA",
    route: "Jaipur → Jodhpur → Udaipur",
    quote: "Fortresses above golden sands, pink palaces, and lakeside heritage havelis.",
    destination: "India",
    citiesCount: 3,
    duration: "6 Days",
    budget: "₹38,000",
    budgetCategory: "budget",
    season: "Winter",
    groupType: "Group",
    moodCategory: "budget",
    styles: ["CULTURE", "FOOD", "ROAD TRIP"],
    creator: TRAVELERS[5], // @priya_travels
    savesCount: 412,
    image: "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=1200&q=85",
    description: "An unforgettable 6-day heritage road trip across Rajasthan's grandest royal cities, exploring pink sandstone palaces, blue alleyways, and sunset boat rides on Lake Pichola.",
    timeline: [
      {
        day: 1,
        title: "Pink City Palaces & Amer Fort",
        location: "Jaipur",
        activities: ["Hawa Mahal facade photos", "Amer Fort hilltop tour", "Pyaaz Kachori tasting at Rawat Sweets"],
        image: "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80",
        timing: "09:00 AM – 07:00 PM",
        cost: "₹6,000",
        notes: "Visit Hawa Mahal early in the morning when sunlight hits the pink front windows."
      },
      {
        day: 2,
        title: "City Palace & Jal Mahal Sunset",
        location: "Jaipur",
        activities: ["Jaipur City Palace Chandra Mahal art tour", "Jantar Mantar sun observatory", "Sunset view of Jal Mahal water palace"],
        image: "https://images.unsplash.com/photo-1603201667141-5a2d4c67337e?auto=format&fit=crop&w=800&q=80",
        timing: "09:30 AM – 06:30 PM",
        cost: "₹5,500",
        notes: "Combined composite monument entry ticket saves 40%."
      },
      {
        day: 3,
        title: "Drive to Blue City Jodhpur",
        location: "Jaipur → Jodhpur",
        activities: ["Highway drive through Thar landscape", "Mehrangarh Fort clifftop walk", "Navchowkiya blue alley photo trail"],
        image: "https://images.unsplash.com/photo-1589308078059-be1415eab4c3?auto=format&fit=crop&w=800&q=80",
        timing: "08:00 AM – 08:00 PM",
        cost: "₹7,200",
        notes: "Zip-line activity available at Mehrangarh fort ramparts."
      },
      {
        day: 4,
        title: "Stepwells & Spice Bazaar",
        location: "Jodhpur",
        activities: ["Toorji Ka Jhalra ancient stepwell coffee", "Clock Tower Sadar Bazaar shopping", "Mirchi Vada street snack"],
        image: "https://images.unsplash.com/photo-1622308644420-a9d59265f247?auto=format&fit=crop&w=800&q=80",
        timing: "09:00 AM – 05:00 PM",
        cost: "₹4,800",
        notes: "Stepwell cafe upper terrace offers best photography angle."
      },
      {
        day: 5,
        title: "Scenic Drive to Lake City Udaipur",
        location: "Jodhpur → Udaipur",
        activities: ["Stop at Ranakpur Marble Jain Temple", "Udaipur City Palace complex", "Sunset boat cruise on Lake Pichola"],
        image: "https://images.unsplash.com/photo-1615836245337-f5b9b2303f10?auto=format&fit=crop&w=800&q=80",
        timing: "08:00 AM – 07:30 PM",
        cost: "₹8,500",
        notes: "Take the 5:30 PM lake boat ride to catch Jag Mandir illuminated."
      },
      {
        day: 6,
        title: "Haveli Breakfast & Farewell",
        location: "Udaipur",
        activities: ["Rooftop Haveli breakfast overlooking Lake Palace", "Saheliyon-ki-Bari fountain gardens", "Udaipur airport departure"],
        image: "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=800&q=80",
        timing: "09:00 AM – 03:00 PM",
        cost: "₹6,000",
        notes: "Handcrafted miniature paintings make high quality traditional gifts."
      }
    ]
  },
  {
    id: "comm-istanbul-4",
    isFeatured: false,
    title: "ISTANBUL BOSPHORUS ESCAPE",
    subtitle: "4 DAYS IN TURKEY",
    route: "Sultanahmet → Galata → Kadıköy",
    quote: "Where East meets West over hot spiced tea, grand bazaars and golden sunsets.",
    destination: "Turkey",
    citiesCount: 1,
    duration: "4 Days",
    budget: "₹32,000",
    budgetCategory: "budget",
    season: "Autumn",
    groupType: "Solo",
    moodCategory: "weekend",
    styles: ["FOOD", "HISTORY", "CULTURE"],
    creator: TRAVELERS[4], // @liam_wander
    savesCount: 196,
    image: "/assets/cities/istanbul.png",
    heroImage: "/assets/cities/istanbul.png",
    description: "A compact 4-day immersion into Istanbul's historic minarets, Bosphorus ferry cruises, aromatic spice bazaars, and bohemian cafes in Kadıköy.",
    timeline: [
      {
        day: 1,
        title: "Heart of Sultanahmet Domes",
        location: "Istanbul (European Side)",
        activities: ["Hagia Sophia interior dome tour", "Blue Mosque courtyard walk", "Turkish delight & tea at historic coffeehouse"],
        image: "/assets/cities/istanbul.png",
        timing: "09:00 AM – 06:00 PM",
        cost: "₹7,500",
        notes: "Modest dress required for Hagia Sophia; scarf provided at entrance."
      },
      {
        day: 2,
        title: "Grand Bazaar & Bosphorus Sunset Cruise",
        location: "Istanbul",
        activities: ["Exploring 4,000 shops in Grand Bazaar", "Egyptian Spice Market aroma trail", "Public ferry ride along Bosphorus Strait to Üsküdar"],
        image: "https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?auto=format&fit=crop&w=800&q=80",
        timing: "10:00 AM – 08:00 PM",
        cost: "₹8,200",
        notes: "Take the cheap public city ferry instead of overpriced private tour boats."
      },
      {
        day: 3,
        title: "Galata Tower & Asian Side Kadıköy",
        location: "Istanbul (Asian Side)",
        activities: ["Galata Tower panorama view", "Karaköy backstreet street art tour", "Ferry to Kadıköy for Meze & Balık Ekmek fish sandwiches"],
        image: "/assets/activities/foodtour.png",
        timing: "09:30 AM – 09:30 PM",
        cost: "₹9,000",
        notes: "Try Moda seaside tea garden in Kadıköy during sunset."
      },
      {
        day: 4,
        title: "Hamam Bath Spa & Farewell",
        location: "Istanbul",
        activities: ["Traditional Kılıç Ali Paşa Hamam scrub spa", "Taksim Square walk", "Airport transfer"],
        image: "https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?auto=format&fit=crop&w=800&q=80",
        timing: "10:00 AM – 04:00 PM",
        cost: "₹7,300",
        notes: "Book Hamam reservation at least 3 days prior."
      }
    ]
  },
  {
    id: "comm-swiss-5",
    isFeatured: false,
    title: "SWISS ALPINE GLACIER EXPRESS",
    subtitle: "8 DAYS IN SWITZERLAND",
    route: "Zurich → Zermatt → Lucerne",
    quote: "Panoramic mountain railways, snow-capped Matterhorn views, and alpine chalets.",
    destination: "Switzerland",
    citiesCount: 3,
    duration: "8 Days",
    budget: "₹1,15,000",
    budgetCategory: "luxury",
    season: "Winter",
    groupType: "Couple",
    moodCategory: "adventure",
    styles: ["ALPINE", "RAIL", "LUXURY"],
    creator: TRAVELERS[3], // @kenji_t
    savesCount: 512,
    image: "/assets/activities/glacier.png",
    heroImage: "https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=1200&q=85",
    description: "An 8-day luxury rail journey through Switzerland onboard the Glacier Express train, taking in the iconic Matterhorn in Zermatt, high alpine bridges, and Lake Lucerne.",
    timeline: [
      {
        day: 1,
        title: "Zurich Old Town & Lake Promenade",
        location: "Zurich",
        activities: ["Bahnhofstrasse luxury shopping walk", "Lindenhof hill viewpoint", "Lake Zurich evening boat cruise"],
        image: "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=800&q=80",
        timing: "11:00 AM – 08:00 PM",
        cost: "₹14,000",
        notes: "Swiss Travel Pass covers all city trams and lake steamboats."
      },
      {
        day: 2,
        title: "Glacier Express to Zermatt",
        location: "Zurich → Zermatt",
        activities: ["Boarding Glacier Express panoramic train", "Crossing 291 mountain bridges", "Check into Matterhorn view chalet"],
        image: "/assets/activities/glacier.png",
        timing: "08:30 AM – 05:00 PM",
        cost: "₹22,000",
        notes: "Seat reservation mandatory on Glacier Express even with Swiss Pass."
      },
      {
        day: 3,
        title: "Gornergrat Bahn & Matterhorn View",
        location: "Zermatt",
        activities: ["Gornergrat cogwheel train up to 3,089m", "Riffelsee mountain lake reflection photo", "Swiss Cheese Fondue dinner"],
        image: "https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=800&q=80",
        timing: "08:00 AM – 07:00 PM",
        cost: "₹16,500",
        notes: "Wear thermal layers; mountain summit temperatures remain below freezing."
      },
      {
        day: 4,
        title: "Glacier Paradise & Ice Palace",
        location: "Zermatt",
        activities: ["Highest cable car station in Europe (3,883m)", "Walk inside glacier ice cave tunnel", "Skiing option or chalet lounge"],
        image: "/assets/activities/paragliding.png",
        timing: "09:00 AM – 04:00 PM",
        cost: "₹15,000",
        notes: "Oxygen level is thinner at summit; pace your walking."
      },
      {
        day: 5,
        title: "Scenic Train to Lake Lucerne",
        location: "Zermatt → Lucerne",
        activities: ["GoldenPass rail route to Lucerne", "Chapel Bridge (Kapellbrücke) wooden covered walk", "Lakeside fish dinner"],
        image: "https://images.unsplash.com/photo-1527668752968-14dc70a27c95?auto=format&fit=crop&w=800&q=80",
        timing: "09:00 AM – 06:00 PM",
        cost: "₹14,500",
        notes: "Visit Chapel bridge early morning to see water reflections without tourists."
      },
      {
        day: 6,
        title: "Mount Pilatus Dragon Ride",
        location: "Lucerne",
        activities: ["Steamboat cruise across Lake Lucerne", "World's steepest cogwheel railway to Mt Pilatus", "Dragon aerial cableway descent"],
        image: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?auto=format&fit=crop&w=800&q=80",
        timing: "08:30 AM – 05:00 PM",
        cost: "₹17,000",
        notes: "The Golden Round Trip ticket includes boat, cogwheel, cableway and bus."
      },
      {
        day: 7,
        title: "Jungfraujoch Day Trip",
        location: "Lucerne → Interlaken",
        activities: ["Eiger Express tricable gondola ride", "Sphinx Observatory view over Aletsch Glacier", "Snow fun park walk"],
        image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80",
        timing: "07:30 AM – 06:00 PM",
        cost: "₹16,000",
        notes: "Check weather webcam at Interlaken station before buying summit ticket."
      },
      {
        day: 8,
        title: "Lucerne Promenade & Departure",
        location: "Lucerne",
        activities: ["Lion Monument sculpture visit", "Swiss chocolate tasting at Bachmann", "Zurich Airport train"],
        image: "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=800&q=80",
        timing: "10:00 AM – 04:00 PM",
        cost: "₹10,000",
        notes: "Purchase Swiss chocolate bars in bulk at local supermarket for savings."
      }
    ]
  },
  {
    id: "comm-amalfi-6",
    isFeatured: false,
    title: "AMALFI COAST CLIFFSIDE DRIFT",
    subtitle: "5 DAYS IN ITALY",
    route: "Positano → Ravello → Capri",
    quote: "Pastel cliffside villas, limoncello tasting, and private catamaran cruises.",
    destination: "Italy",
    citiesCount: 3,
    duration: "5 Days",
    budget: "₹72,000",
    budgetCategory: "mid",
    season: "Summer",
    groupType: "Couple",
    moodCategory: "romantic",
    styles: ["COASTAL", "ROMANTIC", "LUXURY"],
    creator: TRAVELERS[2], // @elena_v
    savesCount: 389,
    image: "/assets/cities/rome.png",
    heroImage: "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1200&q=85",
    description: "A dreamlike 5-day Mediterranean journey along Italy's Amalfi Coast, soaking in Positano's cliffside staircases, Ravello's high gardens, and Capri's Blue Grotto caves.",
    timeline: [
      {
        day: 1,
        title: "Positano Pastel Cliff Check-in",
        location: "Positano",
        activities: ["Check into panoramic cliffside boutique hotel", "Spiaggia Grande beach walk", "Seafood pasta dinner overlooking illuminated cliff villas"],
        image: "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=800&q=80",
        timing: "01:00 PM – 09:30 PM",
        cost: "₹16,000",
        notes: "Porters at Positano dock will carry heavy luggage up staircases for a small fee."
      },
      {
        day: 2,
        title: "Path of the Gods Mountain Hike",
        location: "Bomerano → Nocelle",
        activities: ["Sentiero degli Dei ridge hike high above sea", "Lemon slushie refresh at Nocelle mountain bar", "Bus back to Positano"],
        image: "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&w=800&q=80",
        timing: "08:00 AM – 03:00 PM",
        cost: "₹8,500",
        notes: "Start hike early from Bomerano to walk downhill toward Nocelle with sea ahead."
      },
      {
        day: 3,
        title: "Ravello Gardens & Classical Music",
        location: "Ravello",
        activities: ["Villa Cimbrone Infinity Terrace cliff view", "Villa Rufolo gardens", "Organic Limoncello distillery tasting"],
        image: "/assets/cities/rome.png",
        timing: "09:30 AM – 06:00 PM",
        cost: "₹12,000",
        notes: "Villa Cimbrone terrace offers the most photographed vista on the Mediterranean."
      },
      {
        day: 4,
        title: "Capri Island & Blue Grotto Cruise",
        location: "Capri Island",
        activities: ["Hydrofoil boat from Positano to Capri", "Small wooden boat tour into Blue Grotto cave", "Anacapri chairlift to Monte Solaro peak"],
        image: "/assets/activities/kayaking.png",
        timing: "08:30 AM – 07:00 PM",
        cost: "₹22,000",
        notes: "Blue Grotto entrance depends on ocean tide levels."
      },
      {
        day: 5,
        title: "Amalfi Town Cathedral & Departure",
        location: "Amalfi Town",
        activities: ["Duomo di Amalfi Arab-Norman cathedral", "Handmade paper museum tour", "Private transfer to Naples airport"],
        image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80",
        timing: "10:00 AM – 04:00 PM",
        cost: "₹13,500",
        notes: "Buy ceramic lemon souvenirs from small family shops along main Piazza."
      }
    ]
  },
  {
    id: "comm-iceland-7",
    isFeatured: false,
    title: "ICELAND AURORA & ICE CAVES",
    subtitle: "7 DAYS IN ICELAND",
    route: "Reykjavik → Vik → Glacier Lagoon",
    quote: "Chasing northern lights, geothermal hot springs, and black sand volcanic beaches.",
    destination: "Iceland",
    citiesCount: 4,
    duration: "7 Days",
    budget: "₹88,000",
    budgetCategory: "mid",
    season: "Winter",
    groupType: "Group",
    moodCategory: "adventure",
    styles: ["NATURE", "ROAD TRIP", "ADVENTURE"],
    creator: TRAVELERS[3], // @kenji_t
    savesCount: 467,
    image: "https://images.unsplash.com/photo-1504893524553-b855bce32c67?auto=format&fit=crop&w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1504893524553-b855bce32c67?auto=format&fit=crop&w=1200&q=85",
    description: "An epic 7-day winter road trip along Iceland's Ring Road, featuring Blue Lagoon geothermal spas, Gullfoss waterfalls, black sand beach basalt columns, and midnight Aurora hunts.",
    timeline: [
      {
        day: 1,
        title: "Blue Lagoon Spa & Reykjavik Night",
        location: "Keflavik → Reykjavik",
        activities: ["Silica mud mask soak at Blue Lagoon spa", "Hallgrímskirkja church tower panorama", "Laugavegur street dining"],
        image: "https://images.unsplash.com/photo-1504893524553-b855bce32c67?auto=format&fit=crop&w=800&q=80",
        timing: "11:00 AM – 09:00 PM",
        cost: "₹14,000",
        notes: "Book Blue Lagoon ticket for slot right after airport arrival."
      },
      {
        day: 2,
        title: "Golden Circle Geysers & Waterfalls",
        location: "Golden Circle",
        activities: ["Thingvellir tectonic fissure park", "Haukadalur active Strokkur geyser eruption", "Gullfoss roaring double waterfall"],
        image: "https://images.unsplash.com/photo-1529963183134-61a90db47eaf?auto=format&fit=crop&w=800&q=80",
        timing: "08:30 AM – 05:30 PM",
        cost: "₹11,000",
        notes: "Strokkur geyser erupts reliably every 6 to 10 minutes."
      },
      {
        day: 3,
        title: "South Coast Waterfalls & Black Sand",
        location: "Seljalandsfoss → Vík",
        activities: ["Walking behind Seljalandsfoss waterfall curtain", "Skógafoss 60m drop photo", "Reynisfjara black sand beach basalt columns"],
        image: "https://images.unsplash.com/photo-1476610182048-b716b8518aae?auto=format&fit=crop&w=800&q=80",
        timing: "08:00 AM – 06:00 PM",
        cost: "₹12,500",
        notes: "Keep safe distance from Reynisfjara ocean wave edge; sneaker waves are dangerous."
      },
      {
        day: 4,
        title: "Jökulsárlón Glacier Lagoon Ice Floating",
        location: "Vík → Höfn",
        activities: ["Jökulsárlón glacial lagoon iceberg views", "Diamond Beach glistening ice crystal photography", "Superjeep tour to Vatnajökull natural ice cave"],
        image: "/assets/activities/glacier.png",
        timing: "08:30 AM – 06:30 PM",
        cost: "₹18,000",
        notes: "Crampons and safety helmets provided by glacier superjeep guide."
      },
      {
        day: 5,
        title: "Skaftafell Glacier Hike & Aurora Hunt",
        location: "Skaftafell",
        activities: ["Guided glacier walk with ice axes", "Night Aurora Borealis northern lights guided safari"],
        image: "https://images.unsplash.com/photo-1531366936337-7c91f33a562a?auto=format&fit=crop&w=800&q=80",
        timing: "09:00 AM – Midnight",
        cost: "₹15,000",
        notes: "Clear skies and low light pollution near Skaftafell yield high aurora sighting probability."
      },
      {
        day: 6,
        title: "Lava Tunnel Exploration",
        location: "Raufarhólshellir → Reykjavik",
        activities: ["Raufarhólshellir lava tube cave walk", "Harpa Concert Hall glass architecture", "Nordic seafood dinner"],
        image: "https://images.unsplash.com/photo-1508672019048-805479767ca1?auto=format&fit=crop&w=800&q=80",
        timing: "10:00 AM – 09:00 PM",
        cost: "₹10,500",
        notes: "Lava cave interior temperature is constant 4°C year-round."
      },
      {
        day: 7,
        title: "Reykjavik Bakery & Departure",
        location: "Reykjavik",
        activities: ["Brauð & Co cinnamon roll breakfast", "Souvenir shopping for Icelandic wool sweaters", "Flight departure"],
        image: "https://images.unsplash.com/photo-1499856871958-5b9627545d1a?auto=format&fit=crop&w=800&q=80",
        timing: "09:00 AM – 03:00 PM",
        cost: "₹7,000",
        notes: "Fresh warm cinnamon rolls at Brauð & Co sell out by noon."
      }
    ]
  },
  {
    id: "comm-morocco-8",
    isFeatured: false,
    title: "MOROCCAN MEDINA & SAHARA",
    subtitle: "6 DAYS IN MOROCCO",
    route: "Marrakech → Merzouga → Fes",
    quote: "Terracotta riads, spice labyrinths, and starry desert nights over sand dunes.",
    destination: "Morocco",
    citiesCount: 3,
    duration: "6 Days",
    budget: "₹42,000",
    budgetCategory: "budget",
    season: "Autumn",
    groupType: "Solo",
    moodCategory: "solo",
    styles: ["CULTURE", "DESERT", "FOOD"],
    creator: TRAVELERS[4], // @liam_wander
    savesCount: 310,
    image: "/assets/cities/marrakech.png",
    heroImage: "/assets/cities/marrakech.png",
    description: "A sensory 6-day journey through Marrakech's bustling Jemaa el-Fnaa square, high Atlas mountain passes, camel trekking into Sahara desert dunes, and medieval Fes tanneries.",
    timeline: [
      {
        day: 1,
        title: "Marrakech Medina & Jardin Majorelle",
        location: "Marrakech",
        activities: ["Cobalt blue Jardin Majorelle gardens", "Yves Saint Laurent museum", "Sunset mint tea at Jemaa el-Fnaa rooftop"],
        image: "/assets/cities/marrakech.png",
        timing: "10:00 AM – 09:00 PM",
        cost: "₹7,000",
        notes: "Buy Majorelle tickets online to skip 1-hour entrance queue."
      },
      {
        day: 2,
        title: "Bahia Palace & Spice Souk Trail",
        location: "Marrakech",
        activities: ["Bahia Palace mosaic tile courtyards", "Saadian Tombs", "Exploring Rahba Kedima spice marketplace"],
        image: "https://images.unsplash.com/photo-1597212618440-806262de4f6b?auto=format&fit=crop&w=800&q=80",
        timing: "09:00 AM – 06:00 PM",
        cost: "₹6,200",
        notes: "Polite haggling is customary in Medina souks; start at 50% asking price."
      },
      {
        day: 3,
        title: "Atlas Mountains to Sahara Dunes",
        location: "Marrakech → Merzouga",
        activities: ["Tizi n'Tichka Atlas mountain pass drive", "Aït Benhaddou ancient kasbah mud fortress", "Arriving at Erg Chebbi sand dunes"],
        image: "https://images.unsplash.com/photo-1489493887464-892be6d1daae?auto=format&fit=crop&w=800&q=80",
        timing: "07:00 AM – 07:00 PM",
        cost: "₹9,500",
        notes: "Aït Benhaddou is a UNESCO site featured in Gladiator and Game of Thrones."
      },
      {
        day: 4,
        title: "Sahara Sunset Camel Trek & Camp",
        location: "Merzouga Sahara",
        activities: ["Sunset camel trek across golden Erg Chebbi dunes", "Berber campfire music & star gazing", "Luxury desert tent stay"],
        image: "/assets/activities/safari.png",
        timing: "05:00 PM – Midnight",
        cost: "₹8,800",
        notes: "Desert nights drop in temperature drastically; bring windbreaker fleece."
      },
      {
        day: 5,
        title: "Sunrise Dunes Drive to Fes",
        location: "Merzouga → Fes",
        activities: ["Sahara dune sunrise photo", "Drive through Ziz Valley palm oases", "Check into traditional Fes Riad"],
        image: "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=800&q=80",
        timing: "06:00 AM – 06:30 PM",
        cost: "₹6,000",
        notes: "Fresh dates from Ziz Valley stalls make great road snacks."
      },
      {
        day: 6,
        title: "Fes el-Bali Tannery & Departure",
        location: "Fes",
        activities: ["Chouara Leather Tannery rooftop view", "Al-Attarine Madrasa tilework", "Fes airport departure"],
        image: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80",
        timing: "09:00 AM – 04:00 PM",
        cost: "₹4,500",
        notes: "Tannery leather shops provide mint sprigs to hold near nose for leather aroma."
      }
    ]
  },
  {
    id: "comm-kyoto-9",
    isFeatured: false,
    title: "KYOTO ZEN & TEAHOUSE QUEST",
    subtitle: "5 DAYS IN JAPAN",
    route: "Kyoto",
    quote: "Tranquil morning bamboo forests, traditional wooden ryokans and Matcha ceremonies.",
    destination: "Japan",
    citiesCount: 1,
    duration: "5 Days",
    budget: "₹54,000",
    budgetCategory: "mid",
    season: "Spring",
    groupType: "Solo",
    moodCategory: "slow",
    styles: ["SLOW TRAVEL", "CULTURE", "WELLNESS"],
    creator: TRAVELERS[0], // @maya
    savesCount: 295,
    image: "/assets/cities/kyoto.png",
    heroImage: "/assets/cities/kyoto.png",
    description: "A slow, contemplative 5-day retreat through Kyoto's historic teahouses, zen rock gardens, moss temples, and private kaiseki multi-course dining.",
    timeline: [
      {
        day: 1,
        title: "Ryokan Check-in & Kaiseki Dining",
        location: "Kyoto",
        activities: ["Check into 150-year-old traditional Ryokan", "Tatami room green tea welcome", "9-course seasonal Kaiseki dinner"],
        image: "/assets/cities/kyoto.png",
        timing: "02:00 PM – 09:00 PM",
        cost: "₹15,000",
        notes: "Wear easy slip-on shoes as shoes are removed at ryokan entrance."
      },
      {
        day: 2,
        title: "Arashiyama Bamboo & Tea Ceremony",
        location: "Kyoto",
        activities: ["06:30 AM Arashiyama Bamboo Grove", "Okochi Sanso Villa tea garden", "Tenryu-ji Zen temple gardens"],
        image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=800&q=80",
        timing: "06:30 AM – 04:00 PM",
        cost: "₹8,500",
        notes: "Okochi Sanso ticket includes fresh hot matcha and seasonal sweet."
      },
      {
        day: 3,
        title: "Gion Teahouse Walk & Geisha Heritage",
        location: "Kyoto",
        activities: ["Hanami-koji cobblestone alleywalk", "Kennin-ji oldest zen temple in Kyoto", "Matcha parfait at Tsujiri cafe"],
        image: "https://images.unsplash.com/photo-1492571350019-22de08371fd3?auto=format&fit=crop&w=800&q=80",
        timing: "09:30 AM – 07:00 PM",
        cost: "₹9,200",
        notes: "Respect local signs prohibiting photography of working Geiko/Maiko."
      },
      {
        day: 4,
        title: "Fushimi Inari Torii Dawn Hike",
        location: "Kyoto",
        activities: ["06:00 AM Fushimi Inari 10,000 Torii gate summit walk", "Tofuku-ji valley bridge view", "Kiyomizu-dera wooden balcony view"],
        image: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=800&q=80",
        timing: "06:00 AM – 05:00 PM",
        cost: "₹10,500",
        notes: "Hike to Mount Inari Yotsutsuji intersection for panoramic city view."
      },
      {
        day: 5,
        title: "Philosopher's Path & Departure",
        location: "Kyoto",
        activities: ["Stroll along canal-side Philosopher's Path", "Ginkaku-ji Silver Pavilion sand garden", "Kyoto station bullet train"],
        image: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?auto=format&fit=crop&w=800&q=80",
        timing: "09:00 AM – 03:00 PM",
        cost: "₹10,800",
        notes: "Philosopher's Path cherry blossoms bloom late March to early April."
      }
    ]
  },
  {
    id: "comm-greece-10",
    isFeatured: false,
    title: "GREEK CYCLADES ISLAND HOPPER",
    subtitle: "6 DAYS IN GREECE",
    route: "Santorini → Mykonos",
    quote: "Whitewashed Aegean villas, blue domes, Aegean sailing, and sunset beach clubs.",
    destination: "Greece",
    citiesCount: 2,
    duration: "6 Days",
    budget: "₹68,000",
    budgetCategory: "mid",
    season: "Summer",
    groupType: "Couple",
    moodCategory: "romantic",
    styles: ["ISLAND", "ROMANTIC", "BEACH"],
    creator: TRAVELERS[2], // @elena_v
    savesCount: 356,
    image: "/assets/cities/santorini.png",
    heroImage: "/assets/cities/santorini.png",
    description: "A 6-day Cycladic island hopper pairing Santorini's iconic Oia sunset view and caldera catamaran cruises with Mykonos' Little Venice windmills and golden sandy beaches.",
    timeline: [
      {
        day: 1,
        title: "Oia Sunset & Whitewashed Alleyways",
        location: "Santorini",
        activities: ["Oia blue dome photowalk", "Caldera cliffside infinity pool check-in", "Sunset dinner overlooking Aegean Sea"],
        image: "/assets/cities/santorini.png",
        timing: "02:00 PM – 09:30 PM",
        cost: "₹14,500",
        notes: "Oia sunset spot fills up 1.5 hours before sunset."
      },
      {
        day: 2,
        title: "Red Beach & Volcano Sailing",
        location: "Santorini",
        activities: ["Catamaran cruise around volcanic caldera", "Snorkeling at Red Sand Beach", "Hot springs swim & grilled fish on deck"],
        image: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=800&q=80",
        timing: "10:00 AM – 04:00 PM",
        cost: "₹16,000",
        notes: "Wear dark swimwear for volcanic hot springs as sulfur discolors light fabrics."
      },
      {
        day: 3,
        title: "Santo Vineyard Tasting & Fira Walk",
        location: "Santorini",
        activities: ["Akrotiri Minoan ruins", "Assyrtiko wine tasting at Santo Wines cliff edge", "Fira cable car descent to old port"],
        image: "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=800&q=80",
        timing: "09:30 AM – 07:30 PM",
        cost: "₹10,500",
        notes: "Santo Wines offers 12-wine flight pairing with local cheeses."
      },
      {
        day: 4,
        title: "High-speed Ferry to Mykonos",
        location: "Santorini → Mykonos",
        activities: ["Seajets high-speed ferry ride", "Check into boutique Mykonos town hotel", "Little Venice waterfront cocktails"],
        image: "https://images.unsplash.com/photo-1601581875309-fafbf2d3ed3a?auto=format&fit=crop&w=800&q=80",
        timing: "09:00 AM – 08:00 PM",
        cost: "₹12,000",
        notes: "Little Venice waves lap right against outdoor bar tables."
      },
      {
        day: 5,
        title: "Windmills & Psarou Beach Club",
        location: "Mykonos",
        activities: ["Kato Mili iconic 16th-century windmills photo", "Panagia Paraportiani white church", "Relaxing at Psarou golden beach"],
        image: "/assets/activities/kayaking.png",
        timing: "09:00 AM – 07:00 PM",
        cost: "₹11,000",
        notes: "Windmills look best at early morning light with no crowd."
      },
      {
        day: 6,
        title: "Mykonos Old Town & Departure",
        location: "Mykonos",
        activities: ["Matogianni street shopping", "Greek yogurt & honey breakfast", "Mykonos Airport departure"],
        image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
        timing: "09:00 AM – 03:00 PM",
        cost: "₹4,000",
        notes: "Purchase organic Greek olive oil soaps as traditional gifts."
      }
    ]
  }
];
